### ISSUE TITLE
Licensing Question

### ISSUE THREAD

**Issue by jlarmstrongiv** [bookiza/flippy.JS#1]
What license is flippy.JS under?  I looked in the “LICENSE.markdown” file, but it only stated “Dual license TBD.”  I assume it is to be determined?

**Comment by marvindanig** [comment]
Yes, it's undecided at this point. Will come back on this library in a week or so.

**Comment by jlarmstrongiv** [comment]
Hi Marvin!  Any word on the license for flippy.js?  It would be great to try it on my school's literary magazine.  If it's licensed under under MIT like bookzilla and write-good, that would be amazing :)

**Comment by marvindanig** [comment]
I soooo wish to finish this library right now…:-( 

Unfortunately I'm currently neck deep into this project [https://bubbl.in](https://bubbl.in) - an online cafe of books. Take a look! We have a full code editor (HTML/JS/CSS3) in there, that I find okayish to use. Maybe it will work out for your school project, for now. 

Once I wrap up my responsibilities on Bubblin I'll come back to this library immediately. And yes, OSS-licensing is on the top of our minds.

**Comment by marvindanig** [comment]
And here's a quick article on how to use the web-editor and templates: 

https://blog.marvindanig.com/2016/03/17/how-to-write-a-superbook/

Feel free to reach me on mail/chat anytime if you have a question or need help on your project.

**Comment by jlarmstrongiv** [comment]
Alrighty, thank you for getting back to me!  I've just spent over an hour reviewing Bubblin, and I will probably have some questions when I get more time to review it over the weekend :) thanks again!

**Comment by jlarmstrongiv** [comment]
Thanks for the quick response!  I just spent over an hour reading over bubbl.in, and will probably have questions for you when I have more time to review it over the weekend :) thanks again!
